<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<title>MTG Dataheap</title>
	</head>
	<body>
		<header class="text-center">
			<div class="container">
				<h1>
					MTG Dataheap Scounger
				</h1>
				<p>
					The Dataminaria planeswalker of Magic the Gathering !
				</p>
			</div>
		</header>
		<hr>
		<div class="container">
			<div class="row justify-content-center">
				<div class="col text-center">
					<h2>Staples price < 0.10$ low:</h2>
					<div class="form-group">
						<textarea class="form-control" cols="30" rows="30"><?php echo $wantlist; ?></textarea>
						<button type="button" class="btn btn-dark form-control">Copy to clipboard !</button>
					</div>
				</div>
			</div>
		</div>	
		<footer class="text-center">
			<hr>
			<div>
				<p>
					Made with love by <span>tiboitel</span> @ 2018.
				</p>
			</div>
		</footer>
	</body>
</html>
